# Generated by Django 4.2.27 on 2026-01-09 17:55

from django.db import migrations, models
import django.db.models.deletion
import trips.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TripMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='اسم الرحلة')),
                ('description', models.TextField(verbose_name='وصف البرنامج')),
                ('image', models.ImageField(upload_to='trips/', verbose_name='صورة الرحلة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TripInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_kind', models.CharField(choices=[('overnight', 'رحلة مبيت (فنادق)'), ('daytrip', 'رحلة يوم واحد (بدون مبيت)')], default='overnight', max_length=20, verbose_name='نوع الرحلة')),
                ('start_date', models.DateField(verbose_name='تاريخ الانطلاق')),
                ('end_date', models.DateField(verbose_name='تاريخ العودة')),
                ('price_double', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر البالغ / الغرفة المزدوجة')),
                ('price_single', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='سعر الغرفة المفردة')),
                ('price_triple', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='سعر الشخص الثالث')),
                ('price_child_small', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='سعر الطفل (0-6)')),
                ('price_child_large', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='سعر الطفل (6-12)')),
                ('status', models.CharField(choices=[('active', 'نشطة'), ('completed', 'منتهية/مؤرشفة'), ('full', 'ممتلئة')], default='active', max_length=20)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='trips.tripmaster')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_ref', models.CharField(default=trips.models.generate_booking_ref, max_length=10, unique=True, verbose_name='رقم الحجز')),
                ('customer_name', models.CharField(max_length=100, verbose_name='اسم العميل')),
                ('phone_number', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('adults_double', models.PositiveIntegerField(default=0, verbose_name='عدد (مزدوج/بالغ)')),
                ('adults_single', models.PositiveIntegerField(default=0, verbose_name='عدد (مفرد)')),
                ('children_small', models.PositiveIntegerField(default=0, verbose_name='أطفال (0-6)')),
                ('children_large', models.PositiveIntegerField(default=0, verbose_name='أطفال (6-12)')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الإجمالي')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الحجز')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='trips.tripinstance')),
            ],
        ),
    ]
